global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'wellness-resource-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wellness-resource-service:8083']

  - job_name: 'goal-tracking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['goal-tracking-service:8083']

  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['event-service:8083']

